### GET ORDER BY ID
GET http://localhost:3000/admin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODYwMDI1NSwiZXhwIjoxNzM4NjAzODU1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.E9l_RuM1nJHWsdRutLgVYA8LiRCdRxtnHPwiSr47mGk

### APPROVE ORDER
PATCH http://localhost:3000/admin/approve/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODYwMDI1NSwiZXhwIjoxNzM4NjAzODU1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.E9l_RuM1nJHWsdRutLgVYA8LiRCdRxtnHPwiSr47mGk