### GET ORDER BY ID
GET http://localhost:3000/admin/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODcwODAxNywiZXhwIjoxNzM4NzExNjE3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.OqwfO_2zKSBH7iiOp4gsXPUGQOIpVIcBl0a5wjI1jNk

### APPROVE ORDER
PATCH http://localhost:3000/admin/approve/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODcwODAxNywiZXhwIjoxNzM4NzExNjE3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.OqwfO_2zKSBH7iiOp4gsXPUGQOIpVIcBl0a5wjI1jNk

### REJECT ORDER
PATCH http://localhost:3000/admin/reject/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODcwODAxNywiZXhwIjoxNzM4NzExNjE3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.OqwfO_2zKSBH7iiOp4gsXPUGQOIpVIcBl0a5wjI1jNk
