### GET ORDER BY ID
GET http://localhost:3000/admin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NjgyMDk5LCJleHAiOjE3Mzg2ODU2OTksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.0zAcqp3NK61xNzV_5fFX9opte98uu_m6ido3OEyw1rY

### APPROVE ORDER
PATCH http://localhost:3000/admin/approve/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NjgyMDk5LCJleHAiOjE3Mzg2ODU2OTksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.0zAcqp3NK61xNzV_5fFX9opte98uu_m6ido3OEyw1rY