### SEN UPGRAGE TO INSTRUCTOR REQUEST
POST  http://localhost:3000/account/upgrade-to-instructor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoYW55QGhvdG1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3Mzg3NTkzNTgsImV4cCI6MTczODc2Mjk1OCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.NT7bYz5e2-GK51supHTF6tkYbvlomvuYShQZ-QMuLEY
content-type: application/json

{
  "payment_info": "4111111111111111",
  "national_id":"12345678901234",
  "stripe_info": "acct_9XbD2eRkL0WqYpLm"
}


