### GET ORDER BY ID
GET http://localhost:3000/admin/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODcwODAxNywiZXhwIjoxNzM4NzExNjE3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.OqwfO_2zKSBH7iiOp4gsXPUGQOIpVIcBl0a5wjI1jNk

### APPROVE ORDER
PATCH http://localhost:3000/admin/approve/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NzU5NDg3LCJleHAiOjE3Mzg3NjMwODcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.qoPGSNVIknPX-Z_V69JJcKE0haL9jF3uzQkjfmjXcSg
### REJECT ORDER
PATCH http://localhost:3000/admin/reject/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBob3RtYWlsLmNvbSIsImlhdCI6MTczODcwODAxNywiZXhwIjoxNzM4NzExNjE3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.OqwfO_2zKSBH7iiOp4gsXPUGQOIpVIcBl0a5wjI1jNk
