### TEST TOKEN

GET http://localhost:3000/auth/test-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhaG1lZEBnYW1pbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc5MjIwNzcsImV4cCI6MTczNzkyNTY3NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.SN4qMuS8WALCzKhbwl45G7HfyhaH2uPrw_79ggtyObc
