### TEST TOKEN

GET http://localhost:3000/auth/test-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM3ODU0MjIxLCJleHAiOjE3Mzc4NTc4MjEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.jIDs2nKNtnrzw8FXMHh8WujkXsMAEPR3AcXJGm0Wsh8
