### LOGIN
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "admin@hotmail.com",
  "password": "00000000"
}


### RESET PASSWORD
POST http://localhost:3000/auth/reset-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhaG1lZEBob3RtYWlsLmNvbSIsImlhdCI6MTczODU5OTE3MCwiZXhwIjoxNzM4NjAyNzcwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.iJffkE5Me223QoHkXrOqUJ9ACQ1yF_bvgyRa0mP1e0E

{
    "oldPassword": "00000000",
    "newPassword": "00000000",
    "confirmPassword": "00000000"
}

### REFRESH TOKEN
POST http://localhost:3000/auth/refreshToken
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4NTkxOTgzLCJleHAiOjE3Mzg2Nzc5ODMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.VOawtOT6Bxpnqeb_W2UW_Z8al9M_QOAw36EUS4eVhwA"
}

### SIGN UP
POST localhost:3000/auth/sign-up
content-type: application/json

{
  "email": "admin@hotmail.com",
  "password": "00000000",
  "confirmPassword": "00000000"
}

### FORGET PASSWORD
POST http://localhost:3000/auth/forgot-password
content-type: application/json

{
  "email": "ahmed@hotmail.com"
}

### RESET PASSWORD WITH TOKEN
POST http://localhost:3000/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhaG1lZEBob3RtYWlsLmNvbSIsImlhdCI6MTczODU5OTIwMiwiZXhwIjoxNzM4NTk5NTAyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.theDMwg8tbK6cHU7IvQmFwaVb4UFliz96_rxiN4T8E0
content-type: application/json

{
  "password": "00000000",
  "confirmPassword": "00000000"
}
