### LOGIN
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "ah7608867@gmail.com",
  "password": "1234567890"
}

### FORGET PASSWORD
POST http://localhost:3000/auth/reset-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhaDc2MDg4NjdAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MzgyNDczNTUsImV4cCI6MTczODI1MDk1NSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.RqinhYDIrmt_j0FAyKadc7KQ73-I4v50lFcAOqSSqK8

{
    "oldPassword": "12345678",
    "newPassword": "12345678",
    "confirmPassword": "12345678"
}

### REFRESH TOKEN
POST http://localhost:3000/auth/refreshToken
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM3ODk3NTAxLCJleHAiOjE3Mzc5ODM1MDEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.miGgGK2ioj9pCpuWtrfvT2G9DNB53YsHeKaBkD8FghQ"
}

### SIGN UP
POST localhost:3000/auth/sign-up
content-type: application/json

{
  "email": "ah7608867@gmail.com",
  "password": "12345678",
  "confirmPassword": "12345678",
  "firstName": "ahmed",
  "lastName": "hany"
}

### FORGET PASSWORD
POST http://localhost:3000/auth/forgot-password
content-type: application/json

{
  "email": "ah7608867@gmail.com"
}

### RESET PASSWORD WITH TOKEN
POST http://localhost:3000/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhaDc2MDg4NjdAZ21haWwuY29tIiwiaWF0IjoxNzM4MjU2MDcwLCJleHAiOjE3MzgyNTYzNzAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.ggfPKuHXgVV9rHnQHv0b78YYN6VzSfqmBS4T4Lgx4Rg
content-type: application/json

{
  "password": "1234567890",
  "confirmPassword": "1234567890"
}
