### FORGET PASSWORD

POST http://localhost:3000/auth/forget-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhaG1lZDFAZ21pYWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3Mzc5NzY0ODcsImV4cCI6MTczNzk4MDA4NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.YYgq6DkYvYPEKiEtBDJlgF5DKFXw_OsoJv4UnhYcPTU

{
    "oldPassword": "12345678",
    "newPassword": "123456789",
    "confirmPassword": "123456789"
}