### GET ACCOUNT BY EMAIL

GET http://localhost:3000/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzM4NTQ1OTQ4LCJleHAiOjE3Mzg1NDk1NDgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.VTsaCXGG9vGP8gHxHtOdQk-Gr76gqggFaNHYFuAzl1Q
content-type: application/json

{
  "email": "admin@gmail.com"
}