### GET ACCOUNT BY EMAIL

GET http://localhost:3000/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4NzA3NjA3LCJleHAiOjE3Mzg3MTEyMDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.h2s0FcSJWBE2_ks8kqb7hkNsI0KUb9IJ-9EuYdvxWD8
content-type: application/json

{
  "email": "hany@hotmail.com"
}