### SEN UPGRAGE TO INSTRUCTOR REQUEST
POST  http://localhost:3000/account/upgrade-to-instructor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtb2hhbWVkLmhhbnlAZ21haWwuY29tIiwiaWF0IjoxNzM4NTkyMzcyLCJleHAiOjE3Mzg1OTU5NzIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.oUA6b1FysPAebj2-QcB6jtvkBfIUVpqyBjKxw_E4F9k
content-type: application/json

{
  "payment_info": "4111111111111111",
  "national_id":"12345678901234",
  "stripe_info": "acct_9XbD2eRkL0WqYpLm"
}


