### SEN UPGRAGE TO INSTRUCTOR REQUEST
POST  http://localhost:3000/account/upgrade-to-instructor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJoYW55QGhvdG1haWwuY29tIiwiaWF0IjoxNzM4NzA4NDQxLCJleHAiOjE3Mzg3MTIwNDEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.DKkolQIKNp7K-Tat1LGEWRTKUrE1AOBkVvO-lZ35mHs
content-type: application/json

{
  "payment_info": "4111111111111111",
  "national_id":"12345678901234",
  "stripe_info": "acct_9XbD2eRkL0WqYpLm"
}


