### CREATE NEW ACCOUNT

POST http://localhost:3000/account
content-type: application/json

{
  "email": "ahmed@gamil.com",
  "password": "123456",
  "role": "admin",
  "isActive": true,
  "createdAt": "2021-09-01T00:00:00.000Z",
  "updatedAt": "2021-09-01T00:00:00.000Z"
}